# Generated by Django 5.0 on 2026-01-17 03:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=500)),
                ('location_type', models.CharField(choices=[('centro', 'Centro'), ('afueras', 'Afueras de la Ciudad'), ('montaña', 'Montaña')], db_index=True, default='centro', max_length=20)),
                ('hotel_type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('apart', 'Apart Hotel'), ('cabaña', 'Cabaña'), ('casa', 'Casa/Departamento')], db_index=True, default='hotel', max_length=20)),
                ('stars', models.IntegerField(db_index=True, default=0, help_text='0 = Sin clasificación', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('pet_friendly', models.BooleanField(db_index=True, default=False)),
                ('amenities', models.JSONField(blank=True, default=dict, help_text='JSON con amenities: wifi, parking, breakfast, pool, etc.')),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='JSON con phone, email, website')),
                ('images', models.JSONField(blank=True, default=list, help_text='Array de URLs de imágenes')),
                ('main_image', models.URLField(blank=True, max_length=1000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source_platform', models.CharField(blank=True, help_text='Plataforma de donde se extrajo originalmente', max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='ID en la plataforma externa', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['-stars', 'name'],
                'indexes': [models.Index(fields=['location_type', 'hotel_type'], name='hotels_hote_locatio_463f09_idx'), models.Index(fields=['stars', 'pet_friendly'], name='hotels_hote_stars_0f5b1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('booking', 'Booking.com'), ('airbnb', 'Airbnb'), ('tripadvisor', 'TripAdvisor'), ('local', 'Sitio Local'), ('direct', 'Sitio Oficial')], db_index=True, max_length=20)),
                ('platform_url', models.URLField(max_length=1000)),
                ('price_per_night', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3)),
                ('room_type', models.CharField(blank=True, max_length=200)),
                ('max_guests', models.IntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True, help_text='Precios incluyen desayuno, cancelación gratis, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ['price_per_night'],
                'indexes': [models.Index(fields=['platform', 'is_available'], name='hotels_pric_platfor_51d980_idx'), models.Index(fields=['last_checked'], name='hotels_pric_last_ch_0100b8_idx')],
            },
        ),
    ]
