# Generated by Django 5.2.13 on 2026-04-28 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="hotel",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotels_hote_locatio_463f09_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotels_hote_stars_0f5b1b_idx",
        ),
        migrations.AddField(
            model_name="hotel",
            name="cached_min_price",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="amenities",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="contact_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="external_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="source_platform",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="stars",
            field=models.IntegerField(
                db_index=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["stars", "pet_friendly", "location_type"],
                name="hotels_hote_stars_8fa688_idx",
            ),
        ),
        migrations.AddField(
            model_name="pricealert",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_alerts",
                to="hotels.hotel",
            ),
        ),
    ]
