# Generated by Django 5.2.13 on 2026-04-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_pricealert_alter_hotel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("booking", "Booking.com"),
                            ("airbnb", "Airbnb"),
                            ("tripadvisor", "TripAdvisor"),
                            ("local", "Sitio Local"),
                            ("direct", "Sitio Oficial"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("ARS", "Peso Argentino"),
                            ("USD", "Dólar Estadounidense"),
                            ("EUR", "Euro"),
                        ],
                        default="ARS",
                        max_length=3,
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("is_lowest_30d", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Historial de Precio",
                "verbose_name_plural": "Historial de Precios",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="pricealert",
            options={
                "verbose_name": "Alerta de Precio",
                "verbose_name_plural": "Alertas de Precio",
            },
        ),
        migrations.AddField(
            model_name="pricealert",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pricealert",
            name="target_currency",
            field=models.CharField(
                choices=[
                    ("ARS", "Peso Argentino"),
                    ("USD", "Dólar Estadounidense"),
                    ("EUR", "Euro"),
                ],
                default="ARS",
                max_length=3,
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_pric_hotel_i_34a660_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["user_email"], name="hotels_pric_user_em_560c43_idx"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="hotels.hotel",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["hotel", "platform", "recorded_at"],
                name="hotels_pric_hotel_i_a393b0_idx",
            ),
        ),
    ]
