# Generated by Django 5.2.13 on 2026-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_pricehistory_alter_pricealert_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="platform",
            field=models.CharField(
                choices=[
                    ("booking", "Booking.com"),
                    ("airbnb", "Airbnb"),
                    ("tripadvisor", "TripAdvisor"),
                    ("despegar", "Despegar"),
                    ("expedia", "Expedia"),
                    ("local", "Sitio Local"),
                    ("direct", "Sitio Oficial"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="platform",
            field=models.CharField(
                choices=[
                    ("booking", "Booking.com"),
                    ("airbnb", "Airbnb"),
                    ("tripadvisor", "TripAdvisor"),
                    ("despegar", "Despegar"),
                    ("expedia", "Expedia"),
                    ("local", "Sitio Local"),
                    ("direct", "Sitio Oficial"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
