# Generated by Django 5.0 on 2026-04-29 05:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_add_despegar_expedia_platforms'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hotel',
            new_name='hotel_filter_idx',
            old_name='hotels_hote_stars_8fa688_idx',
        ),
        migrations.RenameIndex(
            model_name='price',
            new_name='price_platform_avail_idx',
            old_name='hotels_pric_platfor_51d980_idx',
        ),
        migrations.RenameIndex(
            model_name='price',
            new_name='price_last_checked_idx',
            old_name='hotels_pric_last_ch_0100b8_idx',
        ),
        migrations.RenameIndex(
            model_name='pricealert',
            new_name='pricealert_hotel_active_idx',
            old_name='hotels_pric_hotel_i_34a660_idx',
        ),
        migrations.RenameIndex(
            model_name='pricealert',
            new_name='pricealert_email_idx',
            old_name='hotels_pric_user_em_560c43_idx',
        ),
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='pricehist_hotel_plat_date_idx',
            old_name='hotels_pric_hotel_i_a393b0_idx',
        ),
        migrations.AddField(
            model_name='hotel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='hotel_search_vector_gin'),
        ),
    ]
