# Generated by Django 5.0 on 2026-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_add_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='platform',
            field=models.CharField(choices=[('booking', 'Booking.com'), ('airbnb', 'Airbnb'), ('tripadvisor', 'TripAdvisor'), ('despegar', 'Despegar'), ('expedia', 'Expedia'), ('amadeus', 'Amadeus'), ('local', 'Sitio Local'), ('direct', 'Sitio Oficial')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='platform',
            field=models.CharField(choices=[('booking', 'Booking.com'), ('airbnb', 'Airbnb'), ('tripadvisor', 'TripAdvisor'), ('despegar', 'Despegar'), ('expedia', 'Expedia'), ('amadeus', 'Amadeus'), ('local', 'Sitio Local'), ('direct', 'Sitio Oficial')], db_index=True, max_length=20),
        ),
    ]
